volumes:
  prowlarr:
  qbittorrent:

services:
  prowlarr:
    depends_on:
      - qbittorrent
    restart: unless-stopped
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "8095:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - prowlarr:/config
    dns:
      - 10.80.0.2
    healthcheck:
      test: curl -sS http://127.0.0.1:9696 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  qbittorrent:
    restart: unless-stopped
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "7080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - qbittorrent:/config
      - /data:/data  # TODO: requires change of ownership to UID:GID
    dns:
        - 10.80.0.2
    healthcheck:
      test: curl -sS http://127.0.0.1:8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  qbittorrent-notify:
    depends_on:
      - qbittorrent
    image: 'adevjoe/qbittorrent-notify:latest'
    environment:
      - QBITTORRENT_PASSWORD
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_HOST=http://qbittorrent:8080
      - CHAT_ID
      - BOT_TOKEN
    restart: unless-stopped
    container_name: qbittorrent-notify
    dns:
    - 10.80.0.2
